name = "RangeHelpers"
uuid = "3a07dd3d-1c52-4395-8858-40c6328157db"
authors = ["Jan Weidner <jw3126@gmail.com> and contributors"]
version = "0.1.6"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter"]
